"""Extended modalities (2026 longevity / prevention standard of care) + zones, concerns and derived markers.

Panels added: advanced blood (cardio-renal-neuro-hormone), VO2 max / CPET & functional tests, body composition
(DEXA + BCA), cardiac CT (CAC + CCTA), MRI (brain, liver PDFF, whole-body), sleep study, proteomic organ age,
cancer screening. Evidence grades: A = guideline-endorsed, B = strong observational/RCT, C = emerging.
"""

EXT_PANELS = {
    "advanced": "Advanced blood (heart, kidney, brain, hormones)",
    "fitness": "VO2 max & functional fitness",
    "bodycomp": "Body composition (DEXA / BCA)",
    "ct": "Cardiac CT (CAC, CCTA)",
    "mri": "MRI (brain, liver, whole-body)",
    "screening": "Screening (sleep study, cancer, ultrasound)",
    "proteomic": "Proteomic organ age",
}

# id: (name, panel, unit, optimal_low, optimal_high, better, aliases, loinc)
EXT_MARKERS = {
    # blood additions used for derived scores
    "ast": ("AST (SGOT)", "blood", "U/L", 10, 25, "low", ["ast (sgot)", "ast", "sgot"], "1920-8"),
    "platelets": ("Platelet count", "blood", "10³/µL", 175, 300, "mid", ["platelet count", "platelets"], "777-3"),
    "neutrophil_pct": ("Neutrophils", "blood", "%", 45, 65, "mid", ["neutrophils"], "770-8"),
    # advanced blood
    "apoa1": ("Apolipoprotein A1", "advanced", "mg/dL", 140, 200, "high", ["apolipoprotein a1", "apoa1"], "1869-7"),
    "ldl_p": ("LDL particle number", "advanced", "nmol/L", 0, 1000, "low", ["ldl particle number", "ldl-p"], "54434-6"),
    "il6": ("Interleukin-6", "advanced", "pg/mL", 0, 2.0, "low", ["interleukin-6", "il-6"], "26881-3"),
    "nt_probnp": ("NT-proBNP", "advanced", "pg/mL", 0, 125, "low", ["nt-probnp"], "33762-6"),
    "hs_troponin": ("hs-Troponin T", "advanced", "ng/L", 0, 10, "low", ["hs-troponin t", "high-sensitivity troponin"], "67151-1"),
    "cystatin_c": ("Cystatin C", "advanced", "mg/L", 0.5, 0.9, "low", ["cystatin c"], "33863-2"),
    "uacr": ("Urine albumin/creatinine ratio", "advanced", "mg/g", 0, 10, "low", ["urine albumin/creatinine ratio", "uacr"], "9318-7"),
    "omega3_index": ("Omega-3 index", "advanced", "%", 8, 12, "high", ["omega-3 index"], ""),
    "ptau217": ("p-tau217", "advanced", "pg/mL", 0, 0.4, "low", ["p-tau217"], ""),
    "nfl": ("Neurofilament light (NfL)", "advanced", "pg/mL", 0, 10, "low", ["neurofilament light (nfl)", "neurofilament light"], ""),
    "igf1": ("IGF-1", "advanced", "ng/mL", 100, 200, "mid", ["igf-1"], "2484-4"),
    "shbg": ("SHBG", "advanced", "nmol/L", 20, 50, "mid", ["shbg"], "13967-5"),
    "free_t": ("Free testosterone", "advanced", "pg/mL", 90, 200, "mid", ["free testosterone"], "2991-8"),
    "dheas": ("DHEA-S", "advanced", "µg/dL", 200, 450, "mid", ["dhea-s"], "2191-5"),
    "mma": ("Methylmalonic acid", "advanced", "nmol/L", 0, 260, "low", ["methylmalonic acid"], "13964-2"),
    "glyca": ("GlycA", "advanced", "µmol/L", 0, 400, "low", ["glyca"], ""),
    # fitness / CPET / functional
    "vo2max_lab": ("VO2 max (CPET)", "fitness", "mL/kg/min", 45, 65, "high", ["vo2 max (cpet)", "vo2 max", "vo2max"], "94133-0"),
    "vt1_hr": ("VT1 heart rate (Zone 2 top)", "fitness", "bpm", None, None, "info", ["vt1 heart rate", "vt1"], ""),
    "vt2_hr": ("VT2 heart rate", "fitness", "bpm", None, None, "info", ["vt2 heart rate", "vt2"], ""),
    "hr_max": ("Peak heart rate", "fitness", "bpm", None, None, "info", ["peak heart rate"], ""),
    "hrr_1min": ("Heart-rate recovery (1 min)", "fitness", "bpm", 18, 60, "high", ["heart-rate recovery (1 min)", "heart rate recovery"], ""),
    "rer_peak": ("Peak RER", "fitness", "", 1.10, 1.30, "info", ["peak rer"], ""),
    "grip": ("Grip strength (best hand)", "fitness", "kg", 40, 70, "high", ["grip strength (best hand)", "grip strength"], ""),
    "gait_speed": ("Gait speed", "fitness", "m/s", 1.2, 2.0, "high", ["gait speed"], ""),
    "sts_30s": ("30-s sit-to-stand", "fitness", "reps", 17, 40, "high", ["30-s sit-to-stand", "sit-to-stand"], ""),
    "balance": ("Single-leg stance (eyes closed)", "fitness", "s", 10, 60, "high", ["single-leg stance (eyes closed)", "single-leg stance"], ""),
    # body composition
    "body_fat_pct": ("Body fat (DEXA)", "bodycomp", "%", 10, 20, "low", ["total body fat (dexa)", "body fat (dexa)"], ""),
    "vat_area": ("Visceral fat area (DEXA)", "bodycomp", "cm²", 0, 100, "low", ["visceral fat area (dexa)", "visceral adipose tissue"], ""),
    "almi": ("Appendicular lean mass index", "bodycomp", "kg/m²", 8.5, 11, "high", ["appendicular lean mass index", "almi"], ""),
    "fmi": ("Fat mass index", "bodycomp", "kg/m²", 3, 6, "low", ["fat mass index", "fmi"], ""),
    "bmd_spine_t": ("BMD T-score (lumbar spine)", "bodycomp", "SD", -1.0, 3.0, "high", ["bmd t-score (lumbar spine)"], ""),
    "bmd_hip_t": ("BMD T-score (total hip)", "bodycomp", "SD", -1.0, 3.0, "high", ["bmd t-score (total hip)"], ""),
    "bca_body_fat": ("Body fat (BCA)", "bodycomp", "%", 10, 20, "low", ["body fat (bca)"], ""),
    "smm": ("Skeletal muscle mass (BCA)", "bodycomp", "kg", 30, 45, "high", ["skeletal muscle mass (bca)"], ""),
    "visceral_level": ("Visceral fat level (BCA)", "bodycomp", "level", 1, 9, "low", ["visceral fat level (bca)"], ""),
    "phase_angle": ("Phase angle (BCA)", "bodycomp", "°", 6.0, 9.0, "high", ["phase angle (bca)"], ""),
    "ecw_tbw": ("ECW/TBW ratio (BCA)", "bodycomp", "", 0.36, 0.39, "low", ["ecw/tbw ratio (bca)"], ""),
    "bmr": ("Basal metabolic rate (BCA)", "bodycomp", "kcal", None, None, "info", ["basal metabolic rate (bca)"], ""),
    # cardiac CT
    "cac": ("Coronary artery calcium (Agatston)", "ct", "AU", 0, 0, "low", ["coronary artery calcium (agatston)", "cac score"], ""),
    "cac_pct": ("CAC percentile (MESA)", "ct", "percentile", 0, 50, "low", ["cac percentile (mesa)"], ""),
    "cad_rads": ("CAD-RADS (CCTA)", "ct", "grade", 0, 0, "low", ["cad-rads (ccta)", "cad-rads"], ""),
    "plaque_vol": ("Total plaque volume (CCTA)", "ct", "mm³", 0, 20, "low", ["total plaque volume (ccta)"], ""),
    "liver_hu": ("Liver attenuation (CT)", "ct", "HU", 50, 75, "high", ["liver attenuation (ct)"], ""),
    "epicardial_fat": ("Epicardial fat volume", "ct", "cm³", 0, 100, "low", ["epicardial fat volume"], ""),
    # MRI
    "liver_pdff": ("Liver fat (MRI-PDFF)", "mri", "%", 0, 5, "low", ["liver fat (mri-pdff)", "mri-pdff"], ""),
    "wmh_fazekas": ("White-matter hyperintensities (Fazekas)", "mri", "grade", 0, 0, "low", ["white-matter hyperintensities (fazekas)"], ""),
    "brain_age_gap": ("Brain-age gap (MRI)", "mri", "years", -5, 0, "low", ["brain-age gap (mri)"], ""),
    "hippocampal_pct": ("Hippocampal volume percentile", "mri", "percentile", 25, 100, "high", ["hippocampal volume percentile"], ""),
    "lvef": ("LV ejection fraction (cardiac MRI)", "mri", "%", 55, 70, "mid", ["lv ejection fraction"], ""),
    "wbmri_findings": ("Whole-body MRI incidental findings", "mri", "count", 0, 0, "low", ["whole-body mri incidental findings"], ""),
    # screening
    "ahi": ("Apnoea-hypopnoea index (home sleep test)", "screening", "events/h", 0, 5, "low", ["apnoea-hypopnoea index", "ahi"], ""),
    "odi": ("Oxygen desaturation index", "screening", "events/h", 0, 5, "low", ["oxygen desaturation index", "odi"], ""),
    "min_spo2": ("Lowest SpO2 (sleep)", "screening", "%", 90, 100, "high", ["lowest spo2 (sleep)"], ""),
    "cimt": ("Carotid IMT (mean)", "screening", "mm", 0.4, 0.7, "low", ["carotid imt (mean)", "cimt"], ""),
    "carotid_plaque": ("Carotid plaque", "screening", "", None, None, "absent", ["carotid plaque"], ""),
    "mced": ("Multi-cancer early detection (MCED)", "screening", "", None, None, "absent", ["multi-cancer early detection (mced)", "mced"], ""),
    "fit": ("Faecal immunochemical test (FIT)", "screening", "", None, None, "absent", ["faecal immunochemical test (fit)"], ""),
    # proteomic organ ages (gap vs chronological, years)
    "org_heart": ("Heart age gap (proteomic)", "proteomic", "years", -5, 0, "low", ["heart age gap"], ""),
    "org_brain": ("Brain age gap (proteomic)", "proteomic", "years", -5, 0, "low", ["brain age gap"], ""),
    "org_liver": ("Liver age gap (proteomic)", "proteomic", "years", -5, 0, "low", ["liver age gap"], ""),
    "org_kidney": ("Kidney age gap (proteomic)", "proteomic", "years", -5, 0, "low", ["kidney age gap"], ""),
    "org_immune": ("Immune age gap (proteomic)", "proteomic", "years", -5, 0, "low", ["immune age gap"], ""),
    "org_artery": ("Artery age gap (proteomic)", "proteomic", "years", -5, 0, "low", ["artery age gap"], ""),
    "org_muscle": ("Muscle age gap (proteomic)", "proteomic", "years", -5, 0, "low", ["muscle age gap"], ""),
    "org_global": ("Global proteomic age gap", "proteomic", "years", -5, 0, "low", ["global proteomic age gap"], ""),
}

EVIDENCE = {  # evidence grade per marker (A guideline / B strong / C emerging)
    **{m: "A" for m in ["ldl", "apob", "hba1c", "glucose", "egfr", "uacr", "cac", "cad_rads", "bmd_spine_t", "bmd_hip_t",
                        "lpa", "nt_probnp", "ahi", "fit", "tsh", "vitd", "hdl", "tg"]},
    **{m: "B" for m in ["hscrp", "vo2max_lab", "grip", "gait_speed", "almi", "vat_area", "liver_pdff", "cystatin_c",
                        "omega3_index", "homa_ir", "insulin", "homocysteine", "ptau217", "hs_troponin", "cimt", "plaque_vol",
                        "wmh_fazekas", "phenoage_lab", "dunedinpace", "grimage", "hrr_1min", "sts_30s"]},
    **{m: "C" for m in ["org_heart", "org_brain", "org_liver", "org_kidney", "org_immune", "org_artery", "org_muscle",
                        "org_global", "glyca", "il6", "nfl", "mced", "brain_age_gap", "telomere", "phase_angle",
                        "shannon", "zonulin", "calprotectin", "mep", "bpa"]},
}

# Multi-band zones (Ultrahuman-style, personalised). Each: list of (upper_exclusive, label, status).
# Optional "sex" key selects a sex-specific list. Bands are clinical categories from guidelines.
ZONES = {
    "tsh": [(0.4, "Low (hyperthyroid range)", "out_of_range"), (2.5, "Optimal", "optimal"), (4.0, "Normal", "in_range"),
            (10, "Elevated (subclinical hypothyroid)", "out_of_range"), (None, "High (hypothyroid)", "out_of_range")],
    "hba1c": [(5.7, "Normal", "optimal"), (6.5, "Prediabetes", "out_of_range"), (None, "Diabetes range", "out_of_range")],
    "glucose": [(70, "Low", "out_of_range"), (100, "Normal", "optimal"), (126, "Impaired fasting glucose", "out_of_range"),
                (None, "Diabetes range", "out_of_range")],
    "ldl": [(70, "Optimal for high-risk", "optimal"), (100, "Optimal", "optimal"), (130, "Near optimal", "in_range"),
            (160, "Borderline high", "out_of_range"), (190, "High", "out_of_range"), (None, "Very high", "out_of_range")],
    "apob": [(80, "Optimal", "optimal"), (100, "Borderline", "in_range"), (130, "High", "out_of_range"), (None, "Very high", "out_of_range")],
    "lpa": [(30, "Normal", "optimal"), (50, "Borderline", "in_range"), (None, "High (inherited risk)", "out_of_range")],
    "hscrp": [(1.0, "Low cardiovascular risk", "optimal"), (3.0, "Average risk", "in_range"), (10, "High risk", "out_of_range"),
              (None, "Acute inflammation likely", "out_of_range")],
    "vitd": [(20, "Deficient", "out_of_range"), (30, "Insufficient", "out_of_range"), (40, "Sufficient", "in_range"),
             (80, "Optimal", "optimal"), (None, "High", "in_range")],
    "homocysteine": [(9, "Optimal", "optimal"), (12, "Normal", "in_range"), (30, "Moderately high", "out_of_range"), (None, "High", "out_of_range")],
    "egfr": [(15, "Kidney failure (G5)", "out_of_range"), (30, "Severely reduced (G4)", "out_of_range"), (60, "Moderately reduced (G3)", "out_of_range"),
             (90, "Mildly reduced (G2)", "in_range"), (None, "Normal (G1)", "optimal")],
    "uacr": [(30, "Normal (A1)", "optimal"), (300, "Moderately increased (A2)", "out_of_range"), (None, "Severely increased (A3)", "out_of_range")],
    "cac": [(1, "Zero — no calcified plaque", "optimal"), (100, "Mild plaque", "out_of_range"), (400, "Moderate plaque", "out_of_range"),
            (None, "Extensive plaque", "out_of_range")],
    "cad_rads": [(1, "CAD-RADS 0 — no plaque", "optimal"), (2, "CAD-RADS 1 — minimal (<25%)", "in_range"),
                 (3, "CAD-RADS 2 — mild (25–49%)", "out_of_range"), (None, "CAD-RADS ≥3 — moderate or worse", "out_of_range")],
    "liver_pdff": [(5, "Normal", "optimal"), (17.4, "Mild steatosis (S1)", "out_of_range"), (22.1, "Moderate (S2)", "out_of_range"),
                   (None, "Severe (S3)", "out_of_range")],
    "liver_hu": [(40, "Moderate–severe steatosis", "out_of_range"), (50, "Possible steatosis", "in_range"), (None, "Normal", "optimal")],
    "vat_area": [(100, "Normal", "optimal"), (160, "Increased risk", "out_of_range"), (None, "High risk", "out_of_range")],
    "bmd_spine_t": [(-2.5, "Osteoporosis", "out_of_range"), (-1.0, "Osteopenia", "out_of_range"), (None, "Normal", "optimal")],
    "bmd_hip_t": [(-2.5, "Osteoporosis", "out_of_range"), (-1.0, "Osteopenia", "out_of_range"), (None, "Normal", "optimal")],
    "almi": {"male": [(7.0, "Low (sarcopenia threshold, EWGSOP2)", "out_of_range"), (8.5, "Below longevity target", "in_range"),
                      (None, "At or above longevity target", "optimal")],
             "female": [(5.5, "Low (sarcopenia threshold, EWGSOP2)", "out_of_range"), (6.8, "Below longevity target", "in_range"),
                        (None, "At or above longevity target", "optimal")]},
    "vo2max_lab": {"male": [(35, "Low (bottom 25% for age)", "out_of_range"), (42, "Below average", "in_range"),
                            (49, "Above average", "in_range"), (55, "High (top 25%)", "optimal"), (None, "Elite (top 2.5%)", "optimal")],
                   "female": [(29, "Low (bottom 25% for age)", "out_of_range"), (35, "Below average", "in_range"),
                              (41, "Above average", "in_range"), (47, "High (top 25%)", "optimal"), (None, "Elite (top 2.5%)", "optimal")]},
    "grip": {"male": [(27, "Low (sarcopenia threshold)", "out_of_range"), (40, "Normal", "in_range"), (None, "Strong", "optimal")],
             "female": [(16, "Low (sarcopenia threshold)", "out_of_range"), (27, "Normal", "in_range"), (None, "Strong", "optimal")]},
    "gait_speed": [(0.8, "Slow (frailty risk)", "out_of_range"), (1.2, "Normal", "in_range"), (None, "Brisk", "optimal")],
    "ahi": [(5, "Normal", "optimal"), (15, "Mild sleep apnoea", "out_of_range"), (30, "Moderate sleep apnoea", "out_of_range"),
            (None, "Severe sleep apnoea", "out_of_range")],
    "cimt": [(0.7, "Normal for age", "optimal"), (0.9, "Increased", "in_range"), (None, "High", "out_of_range")],
    "nt_probnp": [(125, "Normal", "optimal"), (450, "Elevated — clinical review", "out_of_range"), (None, "High", "out_of_range")],
    "ptau217": [(0.4, "Low likelihood of amyloid pathology", "optimal"), (0.63, "Intermediate", "in_range"),
                (None, "High likelihood of amyloid pathology", "out_of_range")],
    "omega3_index": [(4, "Low", "out_of_range"), (8, "Intermediate", "in_range"), (None, "Optimal", "optimal")],
    "wmh_fazekas": [(1, "Fazekas 0 — none", "optimal"), (2, "Fazekas 1 — mild", "in_range"), (None, "Fazekas ≥2 — moderate+", "out_of_range")],
}

# Health-concern groups (many-to-many), from Ultrahuman's grouping, extended to imaging & fitness.
CONCERNS = {
    "Heart & arteries": ["apob", "ldl", "lpa", "hdl", "tg", "hscrp", "homocysteine", "ldl_p", "apoa1", "nt_probnp", "hs_troponin",
                         "cac", "cad_rads", "plaque_vol", "cimt", "carotid_plaque", "epicardial_fat", "lvef", "org_heart", "org_artery"],
    "Blood sugar & metabolism": ["hba1c", "glucose", "insulin", "homa_ir", "tg", "uric_acid", "vat_area", "liver_pdff", "liver_hu", "fto", "tcf7l2", "prs_t2d"],
    "Liver": ["alt", "ast", "ggt", "albumin", "alp", "liver_pdff", "liver_hu", "org_liver"],
    "Kidney": ["creatinine", "egfr", "cystatin_c", "uacr", "uric_acid", "org_kidney"],
    "Inflammation & immunity": ["hscrp", "il6", "glyca", "wbc", "lymph_pct", "neutrophil_pct", "calprotectin", "zonulin", "inflam_clock", "immune_age", "org_immune"],
    "Brain & cognition": ["ptau217", "nfl", "wmh_fazekas", "brain_age_gap", "hippocampal_pct", "apoe", "homocysteine", "b12", "org_brain"],
    "Muscle, bone & mobility": ["almi", "smm", "grip", "gait_speed", "sts_30s", "balance", "bmd_spine_t", "bmd_hip_t", "vitd", "testosterone", "igf1", "phase_angle", "org_muscle"],
    "Fitness & cardiorespiratory": ["vo2max_lab", "hrr_1min", "vt1_hr", "vt2_hr", "hr_max", "rer_peak", "hemoglobin", "ferritin"],
    "Hormones & thyroid": ["tsh", "ft3", "testosterone", "free_t", "shbg", "dheas", "cortisol", "igf1"],
    "Sleep": ["ahi", "odi", "min_spo2", "cortisol", "ferritin", "tsh"],
    "Nutrients": ["vitd", "b12", "mma", "ferritin", "omega3_index", "hemoglobin", "mcv"],
    "Gut": ["shannon", "akkermansia", "faecali", "butyrate", "calprotectin", "zonulin", "candida", "fut2"],
    "Toxins & detox": ["lead", "mercury", "arsenic", "cadmium", "bpa", "mep", "glyphosate", "aflatoxin", "ggt"],
    "Cancer screening": ["mced", "fit", "wbmri_findings"],
    "Ageing pace": ["phenoage_lab", "grimage", "horvath", "dunedinpace", "telomere", "org_global"],
}

# Retest intervals (days) used for follow-up nudges when a marker is out of range / variant.
RETEST_DAYS = {"blood": 90, "advanced": 120, "gut": 180, "bioage": 365, "metals": 180, "toxins": 180, "fitness": 180,
               "bodycomp": 180, "ct": 1825, "mri": 1095, "screening": 365, "proteomic": 365, "genetic": None}

RETEST_PREP = {
    "ast": "Avoid strenuous exercise and alcohol for 3 days before the draw — both raise AST temporarily.",
    "alt": "Avoid alcohol for 3 days before the draw.",
    "ggt": "Avoid alcohol for a week before the draw.",
    "tg": "Fast 10–12 hours; no alcohol the evening before.",
    "glucose": "Fast 8–12 hours; water is fine.",
    "insulin": "Fast 8–12 hours.",
    "hscrp": "Postpone if you've had a cold, infection or hard training in the last 2 weeks.",
    "creatinine": "Avoid heavy training and large meat meals for 24 hours.",
    "cortisol": "Draw between 7 and 9 am.",
    "testosterone": "Draw between 7 and 10 am.",
    "tsh": "Same time of day as last test; hold biotin for 2 days.",
    "vo2max_lab": "No hard training for 48 h, no caffeine for 4 h, light meal 2–3 h before.",
    "vat_area": "Same scanner, morning, fasted and well hydrated — DEXA results drift between machines.",
    "bca_body_fat": "Morning, fasted, after voiding, no exercise — hydration shifts BCA readings by several %.",
}

# Action plan library: each item targets markers, carries an impact grade and contraindications.
ACTIONS = [
    {"kind": "food", "title": "Soluble fibre (oats, psyllium, legumes)", "targets": ["ldl", "apob", "glucose"], "impact": "high",
     "contains": "Beta-glucan, psyllium"},
    {"kind": "food", "title": "Small oily fish (sardines, anchovies, mackerel) 2× a week", "targets": ["omega3_index", "tg", "hscrp"],
     "impact": "high", "contains": "EPA/DHA; among the lowest-mercury fish",
     "caution_if": {"mercury": 3}, "caution": "Your mercury is raised — keep to small fish and avoid tuna, king mackerel, shark and swordfish."},
    {"kind": "food", "title": "Leafy greens and legumes daily", "targets": ["homocysteine", "b12", "shannon"], "impact": "moderate",
     "contains": "Folate, fibre, magnesium"},
    {"kind": "food", "title": "Fermented foods (curd, kanji, idli batter)", "targets": ["shannon", "calprotectin", "zonulin"], "impact": "moderate",
     "contains": "Live cultures"},
    {"kind": "food", "title": "Protein 1.6 g/kg spread over 3 meals", "targets": ["almi", "smm", "grip"], "impact": "high",
     "contains": "Leucine-rich protein", "avoid_if": {"egfr_below": 45}},
    {"kind": "supplement", "title": "Vitamin D3", "dose": "2000–4000 IU/day with a meal", "targets": ["vitd", "bmd_spine_t"], "impact": "high",
     "avoid_if": {"vitd_above": 80}, "only_if_below": {"vitd": 40}},
    {"kind": "supplement", "title": "Omega-3 (EPA+DHA)", "dose": "1–2 g/day", "targets": ["omega3_index", "tg"], "impact": "moderate"},
    {"kind": "supplement", "title": "Methylfolate + methylcobalamin", "dose": "Clinician-guided", "targets": ["homocysteine"], "impact": "high",
     "requires": "mthfr_c677t"},
    {"kind": "supplement", "title": "Psyllium husk", "dose": "5–10 g/day with water", "targets": ["ldl", "apob", "glucose"], "impact": "moderate"},
    {"kind": "supplement", "title": "Creatine monohydrate", "dose": "3–5 g/day", "targets": ["almi", "grip", "smm"], "impact": "moderate",
     "avoid_if": {"egfr_below": 60}},
    {"kind": "supplement", "title": "Iron", "dose": "Clinician-guided; only with confirmed deficiency", "targets": ["ferritin", "hemoglobin"],
     "impact": "high", "only_if_below": {"ferritin": 30}},
    {"kind": "lifestyle", "title": "Zone 2 cardio 3–4× 45 min (below VT1 heart rate)", "targets": ["vo2max_lab", "tg", "homa_ir", "hrv"], "impact": "high"},
    {"kind": "lifestyle", "title": "One weekly 4×4 interval session", "targets": ["vo2max_lab", "hrr_1min"], "impact": "high",
     "avoid_if": {"cac_above": 400}},
    {"kind": "lifestyle", "title": "Strength training 2–3× a week", "targets": ["almi", "grip", "bmd_spine_t", "homa_ir", "sts_30s"], "impact": "high"},
    {"kind": "lifestyle", "title": "10-minute walk after meals", "targets": ["glucose", "hba1c", "homa_ir"], "impact": "moderate"},
    {"kind": "lifestyle", "title": "Alcohol-free weeks", "targets": ["ggt", "alt", "ast", "tg", "liver_pdff", "hrv"], "impact": "high"},
    {"kind": "lifestyle", "title": "Positional therapy / sleep-apnoea evaluation", "targets": ["ahi", "odi", "min_spo2"], "impact": "high"},
    {"kind": "lifestyle", "title": "Glass or steel food containers; no heating in plastic", "targets": ["bpa", "mep"], "impact": "moderate"},
]
